/*
 * Swagger Money Transfer
 * This is a sample money transfer server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: atila.ekimci@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Transaction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2019-07-15T10:22:46.842Z[GMT]")
public class Transaction {
    @JsonProperty("id")
    private int id = 0;

    @JsonProperty("amount")
    private long amount = 0;

    @JsonProperty("fromAccountId")
    private int fromAccountId = 0;

    @JsonProperty("toAccountId")
    private int toAccountId = 0;

    public Transaction id(int id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @JsonProperty("id")
    @Schema(description = "")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Transaction amount(long amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/
    @JsonProperty("amount")
    @Schema(description = "")
    public long getAmount() {
        return amount;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

    public Transaction fromAccountId(int fromAccountId) {
        this.fromAccountId = fromAccountId;
        return this;
    }

    /**
     * Get fromAccountId
     *
     * @return fromAccountId
     **/
    @JsonProperty("fromAccountId")
    @Schema(description = "")
    public int getFromAccountId() {
        return fromAccountId;
    }

    public void setFromAccountId(int fromAccountId) {
        this.fromAccountId = fromAccountId;
    }

    public Transaction toAccountId(int toAccountId) {
        this.toAccountId = toAccountId;
        return this;
    }

    /**
     * Get toAccountId
     *
     * @return toAccountId
     **/
    @JsonProperty("toAccountId")
    @Schema(description = "")
    public int getToAccountId() {
        return toAccountId;
    }

    public void setToAccountId(int toAccountId) {
        this.toAccountId = toAccountId;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Transaction transaction = (Transaction) o;
        return Objects.equals(this.id, transaction.id) &&
                Objects.equals(this.amount, transaction.amount) &&
                Objects.equals(this.fromAccountId, transaction.fromAccountId) &&
                Objects.equals(this.toAccountId, transaction.toAccountId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, amount, fromAccountId, toAccountId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Transaction {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    fromAccountId: ").append(toIndentedString(fromAccountId)).append("\n");
        sb.append("    toAccountId: ").append(toIndentedString(toAccountId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
